### ISSUE TITLE
This is great. VS Code usage: Just one issue with port and my firewall.

### ISSUE THREAD

**Issue by gfmoore** [karaul/fitplotter#1]
Hi, cloned the repo into VS Code. I had an issue with the port numbers you chose being blocked on my BitDefender firewall.

I changed the line (12) in http-server-static.js file to read:
```
portscanner.findAPortNotInUse(**3000**, 4021, '127.0.0.1', function(error, port) {  
```
That is to allow port 3000, rather than 4000 and it all worked wonderfully.

Because it wasn't working, I also opened a command prompt at the folder and did an:
```
npm ci
```
or you could do
```
npm install
```
To ensure the node modules were installed. Not sure this was necessary, though it doesn't do any harm (afaik).

This is a great program, it works really well and you've done some great things with the graphics - very professional.
(I might have stuck the css into a separate folder perhaps.)

Kudos!!!
Gordon

Oh you can close this, it's just for reference if anyone else has issues.

Also, nice of you to include my name in the credits, but really the credit s should go to Jimmy Kane https://github.com/backfit/backfit and the original Pierre Jacquier  https://github.com/pierremtb/easy-fit

All I did was hack their code by removing imports, exports :)

**Comment by karaul** [comment]
Hi Gordon,  

Τhank you for your code - I realized that http-server-static.js is completely unnecessary for the fitplotter.  And tο all the people before who made the parse for the  fit format. 

Υour note about ports is useful in another projects; http-server-static.js is  just a launcher.

**Comment by gfmoore** [comment]
I've posted links to your repo on the Garmin developers forum and also on the Karoo forum. The Karoo Dashboard does not contain any detailed analysis which is not only bizarre, but ridiculous. I've told them to grab your code, incorporate it and then pay you!!!! Let's hope. 

This really is great work (and you say you're learning JS!) It has saved me a ton of effort (though I do miss the challenge. I'd gotten as far as doing a basic graph (in D3) of my speed, but you have included all the zoom stuff, labels and well everything. Marvellous. 

(Not sure what the Pace label is for on the graph, should it be there all the time?)
Great stuff.

**Comment by karaul** [comment]
**All I did was hack their code by removing imports, exports :)**

I did the same,  also I changed buffer, but what I did wrong - did not place my js code intο the head section and did not packed it into the function. My knowledge of JS is not systematic. By reading your code, I finally understood why we need to pack in JS inside the functions 

**Not sure what the Pace label is for on the graph, should it be there all the time**

pace is calculated as well as heart rate eficiency (HRE,  https://drive.google.com/file/d/17wK0y5p7rYlMRBogpZ9yicdnV191E1qx/view?usp=sharing) after the parsing - these metrics are important for runners.

**Comment by karaul** [comment]
**posted links to your repo on the Garmin developers forum and also on the Karoo forum**

I found Garmin developers forum, but where is  the Karoo forum? 

If Karoo offer me to collaborate, I will be happy.  Just now, several friends of mine use fitplotter, and if it the audience will be expanded, it would be great.

**Comment by gfmoore** [comment]
https://support.hammerhead.io/hc/en-us/community/topics 


regards,

Gordon Moore
gm@gordonmoore.co.uk

On 19/02/2021 13:17:54, karaul <notifications@github.com> wrote:
posted links to your repo on the Garmin developers forum and also on the Karoo forum
I found Garmin developers forum, but where is the Karoo forum?
If Karoo offer me to collaborate, I will be happy. Just now, several friends of mine use fitplotter, and if it the audience will be expanded, it would be great.

**Comment by karaul** [comment]
thank you :)
